# Generated by Django 5.0.1 on 2025-11-04 00:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blessedApp', '0003_estado_alter_reserva_estado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reserva',
            name='estado',
            field=models.CharField(max_length=20),
        ),
    ]
