# Generated by Django 5.0.1 on 2025-11-04 00:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blessedApp', '0004_alter_reserva_estado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reserva',
            name='estado',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blessedApp.estado'),
        ),
    ]
